var habits = [
    "Be kind",
    "Keep an open-mind",
    "Eat well",
    "Put your needs first",
    "Exercise",
    "Be honest with yourself",
    "Meditate",
    "Focus on one task at the time",
    "Speak well of others",
    "Listen to understand",
    "Dream big",
    "Choose faith over fear",
    "Be patient",
    "Make the most of now",
    "Judge less",
    "Clean your home",
    "Exercise self-discipline",
    "Tell the truth – at least don’t lie",
    "Smile often",
    "Look on the bright side",
    "Love yourself",
    "Avoid social comparison",
    "Forgive easily",
    "See failure as opportunity",
    "Show gratitude",
    "Take opinions lightly",
    "Think positively",
    "Select friends that lift you up",
    "Drink lots of water",
    "Let go of what can't be changed",
    "Believe in yourself",
    "Have a healthy sleeping pattern",
    "Improve yourself each day a little from yesterday",
    "Practice laughing"
];
